# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JuuzSTHVEfAwaCriOa_-4Qco-QnnNTw
"""

import numpy as np

import pandas as pd

df=pd.read_csv("/content/titanic.csv")

df

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

df.columns

sns.countplot(x = df['Survived'])

df['Survived'].value_counts()

df['Survived'].value_counts().plot(kind='pie' ,autopct='%.2f')

plt.hist(x=df['Age'])

sns.distplot(x=df['Age'])

sns.distplot(x=df['Age'], hist=False)

sns.boxplot(x=df['Age'])